"""initial_schema

Revision ID: 0a3e9a1488ea
Revises:
Create Date: 2026-03-16 23:23:25.223625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3e9a1488ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('data', sa.JSON(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_source', 'events', ['source_id'], unique=False)
    op.create_index('idx_events_ts', 'events', ['ts'], unique=False)
    op.create_index('idx_events_type', 'events', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_type', table_name='events')
    op.drop_index('idx_events_ts', table_name='events')
    op.drop_index('idx_events_source', table_name='events')
    op.drop_table('events')
    op.drop_table('sources')
    # ### end Alembic commands ###
